### ISSUE TITLE
Diagramme de classes UML

### ISSUE THREAD

**Issue by AmiralBl3ndic** [opsilonn/Moodle_2#7]
Il faut faire un schéma UML de la structure du projet.

On avancera mieux une fois ça fait

**Comment by opsilonn** [comment]
Un premier jet du diagramme UML a été fait. Il correspond aux éléments requis pour la version.1 ; reste donc à s'assurer de l'approbation de l'équipe pour clore cette "issue".

**Comment by AmiralBl3ndic** [comment]
Résolu au [commit 8adf88934c](https://github.com/opsilonn/Moodle_2/commit/8adf88934cedb653d6a0d0f6ed3e602980009a9b)
